# Generated by Django 4.2 on 2023-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabbageCheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('vendor', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=30)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=4)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=4)),
                ('calories', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('vendor', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=30)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=4)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=4)),
                ('calories', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kefir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('vendor', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=30)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=4)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=4)),
                ('calories', models.IntegerField()),
                ('volume', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('vendor', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=30)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=4)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=4)),
                ('calories', models.IntegerField()),
                ('volume', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
