# Generated by Django 4.2 on 2023-06-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbagecheese',
            name='calories',
            field=models.IntegerField(help_text='f.e. 999'),
        ),
        migrations.AlterField(
            model_name='cabbagecheese',
            name='category',
            field=models.CharField(help_text='f.e. cheese', max_length=30),
        ),
        migrations.AlterField(
            model_name='cabbagecheese',
            name='fat',
            field=models.DecimalField(decimal_places=1, help_text='f.e. 999.9', max_digits=4),
        ),
        migrations.AlterField(
            model_name='cabbagecheese',
            name='image',
            field=models.URLField(help_text="f.e. 'http:/static.exampl.com/77577mhf.jpeg'"),
        ),
        migrations.AlterField(
            model_name='cabbagecheese',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='f.e. 9999.99', max_digits=6),
        ),
        migrations.AlterField(
            model_name='cabbagecheese',
            name='protein',
            field=models.DecimalField(decimal_places=1, help_text='f.e. 999.9', max_digits=4),
        ),
        migrations.AlterField(
            model_name='cabbagecheese',
            name='title',
            field=models.CharField(help_text='f.e Product', max_length=250),
        ),
        migrations.AlterField(
            model_name='cabbagecheese',
            name='vendor',
            field=models.CharField(help_text='f.e. Product&Health', max_length=150),
        ),
        migrations.AlterField(
            model_name='cabbagecheese',
            name='weight',
            field=models.IntegerField(help_text='f.e 999'),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='calories',
            field=models.IntegerField(help_text='f.e. 999'),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='category',
            field=models.CharField(help_text='f.e. cheese', max_length=30),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='fat',
            field=models.DecimalField(decimal_places=1, help_text='f.e. 999.9', max_digits=4),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='image',
            field=models.URLField(help_text="f.e. 'http:/static.exampl.com/77577mhf.jpeg'"),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='f.e. 9999.99', max_digits=6),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='protein',
            field=models.DecimalField(decimal_places=1, help_text='f.e. 999.9', max_digits=4),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='title',
            field=models.CharField(help_text='f.e Product', max_length=250),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='vendor',
            field=models.CharField(help_text='f.e. Product&Health', max_length=150),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='weight',
            field=models.IntegerField(help_text='f.e 999'),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='calories',
            field=models.IntegerField(help_text='f.e. 999'),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='category',
            field=models.CharField(help_text='f.e. cheese', max_length=30),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='fat',
            field=models.DecimalField(decimal_places=1, help_text='f.e. 999.9', max_digits=4),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='image',
            field=models.URLField(help_text="f.e. 'http:/static.exampl.com/77577mhf.jpeg'"),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='f.e. 9999.99', max_digits=6),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='protein',
            field=models.DecimalField(decimal_places=1, help_text='f.e. 999.9', max_digits=4),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='title',
            field=models.CharField(help_text='f.e Product', max_length=250),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='vendor',
            field=models.CharField(help_text='f.e. Product&Health', max_length=150),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='volume',
            field=models.DecimalField(decimal_places=1, help_text='f.e 9999.9', max_digits=5),
        ),
        migrations.AlterField(
            model_name='milk',
            name='calories',
            field=models.IntegerField(help_text='f.e. 999'),
        ),
        migrations.AlterField(
            model_name='milk',
            name='category',
            field=models.CharField(help_text='f.e. cheese', max_length=30),
        ),
        migrations.AlterField(
            model_name='milk',
            name='fat',
            field=models.DecimalField(decimal_places=1, help_text='f.e. 999.9', max_digits=4),
        ),
        migrations.AlterField(
            model_name='milk',
            name='image',
            field=models.URLField(help_text="f.e. 'http:/static.exampl.com/77577mhf.jpeg'"),
        ),
        migrations.AlterField(
            model_name='milk',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='f.e. 9999.99', max_digits=6),
        ),
        migrations.AlterField(
            model_name='milk',
            name='protein',
            field=models.DecimalField(decimal_places=1, help_text='f.e. 999.9', max_digits=4),
        ),
        migrations.AlterField(
            model_name='milk',
            name='title',
            field=models.CharField(help_text='f.e Product', max_length=250),
        ),
        migrations.AlterField(
            model_name='milk',
            name='vendor',
            field=models.CharField(help_text='f.e. Product&Health', max_length=150),
        ),
        migrations.AlterField(
            model_name='milk',
            name='volume',
            field=models.DecimalField(decimal_places=1, help_text='f.e 9999.9', max_digits=5),
        ),
    ]
